### ISSUE TITLE
wrong  sources via forge.ocamlcore.org

### ISSUE THREAD

**Issue by klartext** [ygrek/ocaml-mysql#7]
It's possible to get file
https://forge.ocamlcore.org/frs/download.php/1500/ocaml-mysql-1.2.1.tar.gz
and it has md5sum   81d3bf217e4ed1829b9ea19f037dce65,
which is the md5sum for release 1.2.0.

Disabling the old link, so that only the new link to
http://ygrek.org.ua/p/release/ocaml-mysql/ocaml-mysql-1.2.1.tar.gz
is available, ( sources there have md5sum    776d07219ac3a6ffa000811defd91eb3 )
would help to avoid confusion to those, who have the old link,
try to get new sources but get the old one.

A 404-error for forge.ocamlcore.org would be better.

**Comment by ygrek** [comment]
Where did you get the first link?
Correct link for ocaml-mysql 1.2.1 on the forge is https://forge.ocamlcore.org/frs/download.php/1625/ocaml-mysql-1.2.1.tar.gz
Apparently ocamlcore site uses the number in url as the actual identifier of the download, and the rest of the url can be any filename, this is a pretty widespread practice.
